apiVersion: v1
kind: Service
metadata:
  name: vulapp-service-cl
  namespace: vulapp-namespace-cl
spec:
  selector:
    app: vulapp-cl
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort
