apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ns2
  namespace: ns1
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ns2
