apiVersion: v1
kind: Service
metadata:
  name: vulapp-service-full
  namespace: vulapp-namespace-full
spec:
  selector:
    app: vulapp-full
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort
